language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t islamgamal88/dr -f Dockerfile.dev .

scripts:
  - docker run -e CI=true islamgamal88/dr npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "dr"
  env: "Dr-env"
  bucket_name: "elasticbeanstalk-us-east-2-614878802407"
  bucket_path: "dr"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
