language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t islamgamal88/dr -f Dovkerfile.dev .

scripts:
  - docker run -e CI=true islamgamal88/dr npm run test -- --coverage
